magic_the_gathering:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /Users/milindsoorya/.gc/magic-the-gathering-381611-5380f0468b17.json # Exchange with path to your Google Cloud credentials, created under step 1
      project: magic-the-gathering-381611
      dataset: mtg_card_data_dbt
      threads: 1
      timeout_seconds: 300
      location: europe-west6
      priority: interactive
